### ISSUE TITLE
Runtime error "Cannot set a non-string value as the PAD token"

### ISSUE THREAD

**Issue by nancheng58** [HestiaSky/LLaMA_SRank#4]
Dear authors,
Thanks for your nice work! I have already cloned this repo and downloaded the 'Platypus2-70B-instruct' model. However, I encounter (meet) with the following error when running the 'fine-turning.sh':
```python
Traceback (most recent call last):
  File "finetune.py", line 245, in <module>
    fire.Fire(train)
  File "/data/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data/anaconda3/envs/llama/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "finetune.py", line 118, in train
    model = LLM4Rec(
  File "/data/baseline/E4SRec/model.py", line 42, in __init__
    self.llama_tokenizer.pad_token = 0
  File "/data/anaconda3/envs/llama/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1145, in pad_token
    raise ValueError("Cannot set a non-string value as the PAD token")
ValueError: Cannot set a non-string value as the PAD token
```
It seems like the token cannot be the number.

**Comment by nancheng58** [comment]
I replaced the PAD token from 0 to '0' and solved this issue.  Due to the resourse restricted, I replaced the basemodel to Llama2-13B to train and evaluate the E4SRec, but the gained result is very poor.
The finetune script is
```python
torchrun --nproc_per_node=8 --master_port=1907 finetune.py \
    --base_model /data06/Llama-2-13b-hf \
    --data_path Beauty \
    --task_type sequential \
    --output_dir ./LLM4Rec \
    --batch_size 16 \
    --micro_batch_size 1 \
    --num_epochs 1 \
    --learning_rate 0.0003 \
    --cutoff_len 4096 \
    --val_set_size 0 \
    --lora_r 16 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[gate_proj, down_proj, up_proj]' \
    --train_on_inputs False \
    --add_eos_token False \
    --group_by_length False \
    --prompt_template_name alpaca \
    --lr_scheduler 'cosine' \
    --warmup_steps 100 \
    --wandb_project E4SRec
```
The infer script is 
```python
torchrun --nproc_per_node=8 --master_port=1234 inference.py \
    --base_model /data06/Llama-2-13b-hf \
    --data_path Beauty \
    --task_type sequential \
    --checkpoint_dir ./LLM4Rec/ \
    --cache_dir cache_dir/ \
    --output_dir ./LLM4Rec/ \
    --batch_size 16 \
    --micro_batch_size 1
```
The reported results is that
```bash
Evaluation for User: 

Precision@1: 8.9433439162903e-05 
 Recall@1: 8.9433439162903e-05 
 MRR@1: 8.9433439162903e-05 
 MAP@1: 8.9433439162903e-05 
 NDCG@1: 8.9433439162903e-05 

Precision@5: 8.9433439162903e-05 
 Recall@5: 0.00044716719581451504 
 MRR@5: 0.0001974988448180775 
 MAP@5: 0.0001974988448180775 
 NDCG@5: 0.0002586554819987668 

Precision@10: 8.943343916290303e-05 
 Recall@10: 0.0008943343916290301 
 MRR@10: 0.00025114116358582666 
 MAP@10: 0.00025114116358582666 
 NDCG@10: 0.0003971278706389283 

Precision@20: 7.825425926754018e-05 
 Recall@20: 0.0015650851853508028 
 MRR@20: 0.0002965062025846168 
 MAP@20: 0.0002965062025846168 
 NDCG@20: 0.0005650891080215324 

Precision@100: 7.154675133032246e-05 
 Recall@100: 0.007154675133032241 
 MRR@100: 0.00040016219874475093 
 MAP@100: 0.00040016219874475093 
 NDCG@100: 0.0015212688144377391
```

**Comment by Xu107** [comment]
The similar issues here.I would like to ask if there are any issues with the evaluation? There are too many decimals,like 0.000.

**Comment by HestiaSky** [comment]
If you want to use a smaller base model, please use **garage-bAInd/Platypus2-13B** or **garage-bAInd/Platypus2-7B** instead.
Original LLaMA2 is not instruction-tuned and can not get desirable results.

**Comment by arpita739** [comment]
**Understanding the Problem**

**What is pad_token and pad_token_id?**
pad_token: A string representing the token used for padding sequences to a uniform length (e.g., <|eos|> or [PAD]). This is necessary for batch processing in NLP models.
pad_token_id: An integer representing the token's ID in the tokenizer's vocabulary, derived from pad_token.

**What’s Happening in Your Code?**
In HuggingFacePipeline.from_model_id, the method loads a model and tokenizer using AutoModelForCausalLM.from_pretrained and AutoTokenizer.from_pretrained.
It then tries to set tokenizer.pad_token_id = model.config.eos_token_id to ensure the tokenizer has a padding token ID aligned with the model’s end-of-sequence token.
However, pad_token_id is a read-only property in the transformers library’s PreTrainedTokenizerBase class. Directly setting it isn’t allowed because it’s derived from pad_token, which must be a string.
When the code attempts this assignment, the tokenizer’s __setattr__ method raises the ValueError because it expects pad_token to be set as a string first.

**Why Does This Happen?**
Some models, like "meta-llama/Llama-3.1-8B-Instruct", may not define a pad_token by default in their tokenizer. In such cases, the pad_token is None, and setting pad_token_id directly without defining pad_token causes an inconsistency that the library rejects.

**Traceback Insight:**
The error occurs in transformers/tokenization_utils_base.py, line 1081, within the __setattr__ method, confirming that the issue is related to attribute setting in the tokenizer.

**Solution**
To fix this, you need to ensure the tokenizer has a valid pad_token (a string) before the pipeline is created. The simplest approach is to set tokenizer.pad_token to the eos_token (end-of-sequence token) if it’s not already defined. However, since HuggingFacePipeline.from_model_id internally sets pad_token_id and causes the error, a better solution is to:

Load the tokenizer and model manually.
Set the pad_token explicitly.
Create a transformers.pipeline object with the pre-configured tokenizer and model.
Pass this pipeline to HuggingFacePipeline instead of using from_model_id.
This avoids the problematic line in from_model_id and gives you full control over the setup.
